app:
  env:  "development"
  port: 8080
  debug: true

mongodb:
  host: "mongodb://localhost:"
  port: "27017"
  databaseName: "Movies"

postgrsdb: 
  host: "localhost"
  port: "3306"
  user: "postgres"
  password: "admin"
  # databaseName: ""

log:
  level: "debug"
  format: "json"